### ISSUE TITLE
Add Github Pages version of HRM Fiddle for testing

### ISSUE THREAD

**Issue by sixlettervariables** [sixlettervariables/hrmsandbox#15]

**Comment by sixlettervariables** [comment]
Closed by b0d2fe5.

**Comment by sixlettervariables** [comment]
Currently aligned to the `next-gen-hrm-fiddle` branch:

http://christopherwatford.com/hrmsandbox/

**Comment by nrkn** [comment]
Looks great! Was just having a play, couldn't break it :P
