### ISSUE TITLE
Support comments

### ISSUE THREAD

**Issue by MulleDK19** [sixlettervariables/hrmsandbox#24]
This shows correctly:
```-- Comment```

This fails:
```INBOX -- Comment```

**EDIT:** I guess this really belongs on the viewer.

**Comment by sixlettervariables** [comment]
@MulleDK19 as in my grammar parses it, but the pretty-viewer does not?

**Comment by MulleDK19** [comment]
Yeah. The viewer shows the entire line as invalid.

**Comment by sixlettervariables** [comment]
If you could raise this on https://github.com/AlanDeSmet/human-resource-machine-viewer that would be great, as that's the upstream package I use for the viewer.
