### ISSUE TITLE
A shout out about other HRM projects

### ISSUE THREAD

**Issue by atesgoral** [sixlettervariables/hrmsandbox#3]
CC: @nrkn

A bit of an intersection with this project: https://github.com/nrkn/hrm-cpu

Game level data: https://github.com/atesgoral/hrm-level-data

Solutions & size/speed hacks for levels: https://github.com/atesgoral/hrm-solutions

Robots rule!

**Comment by nrkn** [comment]
@sixlettervariables this is very cool. Did you go with your own syntax over the in-game one for any particular reason? 

I started with my own syntax too - I didn't realise that there was an in-game asm syntax until I saw the solutions project that @atesgoral did!

An advantage to using the in-game syntax is that there is a wealth of files to test against your engine - both by copying solutions from your own game, and also the ones in the solutions project. See the tests in my project to see how I use the expected input/output from the actual game (in the level data project linked above) to test my engine

I may implement some of your error checking, at the moment I have next to none.

**Comment by sixlettervariables** [comment]
I'll revise my grammar today to meet the game's, I just hadn't seen it.
I'll also see about breaking it out so other projects can use it.

Good to see I'm not alone in my endeavors!

**Comment by atesgoral** [comment]
:+1: @sixlettervariables

**Comment by nrkn** [comment]
I'm glad you went with pegjs, it's the only js expression grammar tool I'm familiar with!

**Comment by sixlettervariables** [comment]
Check out https://github.com/sixlettervariables/hrmsandbox/tree/revise-grammar-to-game-standard
